export const LIST_CATEGORIES = "LIST_CATEGORIES";
export const SET_CATEGORY_ACTIVE = "SET_CATEGORY_ACTIVE";

export const IS_CURRENCY_OPEN = "IS_CURRENCY_OPEN";
export const SET_CURRENCY = "SET_CURRENCY";

export const SET_ACTIVE_IMAGE = "SET_ACTIVE_IMAGE";
export const SET_ACTIVE_SIZE = "SET_ACTIVE_SIZE";
