//CATEGORIES
export const LIST_CATEGORIES = "LIST_CATEGORIES";
export const SET_CATEGORY_ACTIVE = "SET_CATEGORY_ACTIVE";

// CURRENCY
export const IS_CURRENCY_OPEN = "IS_CURRENCY_OPEN";
export const SET_CURRENCY = "SET_CURRENCY";

// PRODUCT
export const SET_ACTIVE_IMAGE = "SET_ACTIVE_IMAGE";
export const SET_ACTIVE_SIZE = "SET_ACTIVE_SIZE";

// CART
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_ONE_PRODUCT = "ADD_ONE_PRODUCT";
export const REMOVE_ONE_PRODUCT = "REMOVE_ONE_PRODUCT";
export const CHECK_OUT = "CHECK_OUT";
